/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.contactInfo;
import models.employeeDetails;
import models.employeeDirectory;

/**
 *
 * @author athipathi
 */
public class ViewPanel extends javax.swing.JPanel {

    employeeDirectory employeeList,filteredList;
    employeeDetails emp,employee;
    contactInfo contact;
    int empId;
    public ViewPanel(employeeDirectory empList) {
        initComponents();
        employeeList = empList;
        displayEmployees(employeeList);
    }
    
    public void displayEmployees(employeeDirectory tableList){
         DefaultTableModel model = (DefaultTableModel) empTable.getModel();
         model.setRowCount(0);         
         for(employeeDetails emp: tableList.getEmployeeList())
         {
             Object[] row = new Object[11];
             row[0]=emp.getEmployeeID();
             row[1]=emp.getName();
             row[2]=emp.getAge();
             row[3]=emp.getGender();
             row[4]=emp.getStartDate();
             row[5]=emp.getLevel();
             row[6]=emp.getTeamInfo();
             row[7]=emp.getPositionTitle();
             contactInfo contactDetails= emp.getContact();
             row[8]= contactDetails.getPhoneNumber();
             row[9]= contactDetails.getEmailID();
             row[10]=emp.getProfilePhoto();
             
             model.addRow(row);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txt_NameSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_EmpIDSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_emailSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        empPanel = new javax.swing.JPanel();
        labelCreate = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelEmpID = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelStartDate = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        labelTeamInfo = new javax.swing.JLabel();
        labelPosition = new javax.swing.JLabel();
        labelMobile = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        label_displayName = new javax.swing.JLabel();
        label_displayEmpID = new javax.swing.JLabel();
        label_displayAge = new javax.swing.JLabel();
        label_displayGender = new javax.swing.JLabel();
        label_displayDate = new javax.swing.JLabel();
        label_displayLevel = new javax.swing.JLabel();
        label_displayTeamInfo = new javax.swing.JLabel();
        label_displayPosition = new javax.swing.JLabel();
        label_displayPhone = new javax.swing.JLabel();
        label_displayEmail = new javax.swing.JLabel();
        profilePhoto = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        updatePanel = new javax.swing.JPanel();
        labelCreate1 = new javax.swing.JLabel();
        labelName1 = new javax.swing.JLabel();
        labelEmpID1 = new javax.swing.JLabel();
        labelAge1 = new javax.swing.JLabel();
        labelGender1 = new javax.swing.JLabel();
        labelStartDate1 = new javax.swing.JLabel();
        labelLevel1 = new javax.swing.JLabel();
        labelTeamInfo1 = new javax.swing.JLabel();
        labelPosition1 = new javax.swing.JLabel();
        labelMobile1 = new javax.swing.JLabel();
        labelEmail1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        errTxt = new javax.swing.JLabel();
        errTxt5 = new javax.swing.JLabel();
        errTxt6 = new javax.swing.JLabel();
        errTxt7 = new javax.swing.JLabel();
        errTxt8 = new javax.swing.JLabel();
        errTxt9 = new javax.swing.JLabel();
        fixed_EmpID = new javax.swing.JLabel();
        fixed_Gender = new javax.swing.JLabel();
        fixed_Date = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        fixed_Age = new javax.swing.JLabel();
        displayPic = new javax.swing.JLabel();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        listPanel.setBackground(new java.awt.Color(255, 255, 255));

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Age", "Gender", "Start Date", "Level", "Team Info", "Position ", "Phone Number", "Email", "Photo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        empTable.setColumnSelectionAllowed(true);
        empTable.getTableHeader().setReorderingAllowed(false);
        empTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(empTable);
        empTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (empTable.getColumnModel().getColumnCount() > 0) {
            empTable.getColumnModel().getColumn(6).setResizable(false);
            empTable.getColumnModel().getColumn(10).setResizable(false);
            empTable.getColumnModel().getColumn(10).setPreferredWidth(0);
        }

        btnSearch.setBackground(new java.awt.Color(255, 153, 0));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txt_NameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameSearchActionPerformed(evt);
            }
        });
        txt_NameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_NameSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NameSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Search by Employee Name:");

        jLabel2.setText("Search by Employee ID");

        txt_emailSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailSearchActionPerformed(evt);
            }
        });
        txt_emailSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailSearchKeyReleased(evt);
            }
        });

        jLabel3.setText("Search by Employee Email:");

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(listPanelLayout.createSequentialGroup()
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(txt_EmpIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(listPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_emailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_emailSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_EmpIDSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );

        jTabbedPane1.addTab("tab1", listPanel);

        empPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelCreate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelCreate.setText("Employee Details");

        labelName.setText("Name");

        labelEmpID.setText("Employee ID");

        labelAge.setText("Age");

        labelGender.setText("Gender");

        labelStartDate.setText("Start Date");

        labelLevel.setText("Level");

        labelTeamInfo.setText("Team Info");

        labelPosition.setText("Position Title");
        labelPosition.setToolTipText("");

        labelMobile.setText("Phone Number");

        labelEmail.setText("Email ID");

        label_displayName.setToolTipText("");

        label_displayEmpID.setToolTipText("");

        label_displayAge.setToolTipText("");

        label_displayGender.setToolTipText("");

        label_displayDate.setToolTipText("");

        label_displayLevel.setToolTipText("");

        label_displayTeamInfo.setToolTipText("");

        label_displayPosition.setToolTipText("");

        label_displayPhone.setToolTipText("");

        label_displayEmail.setToolTipText("");

        profilePhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpdate.setBackground(new java.awt.Color(255, 153, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout empPanelLayout = new javax.swing.GroupLayout(empPanel);
        empPanel.setLayout(empPanelLayout);
        empPanelLayout.setHorizontalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayGender, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayDate, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addComponent(labelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        empPanelLayout.setVerticalGroup(
            empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayName))
                        .addGap(18, 18, 18)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayEmpID))
                        .addGap(18, 18, 18)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayAge))
                        .addGap(18, 18, 18)
                        .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_displayGender)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(profilePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayDate))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayLevel)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayTeamInfo)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayPosition))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayPhone))
                .addGap(18, 18, 18)
                .addGroup(empPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_displayEmail))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", empPanel);

        updatePanel.setBackground(new java.awt.Color(255, 255, 255));

        labelCreate1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelCreate1.setText("Update Employee Profile");

        labelName1.setText("Name");

        labelEmpID1.setText("Employee ID");

        labelAge1.setText("Age");

        labelGender1.setText("Gender");

        labelStartDate1.setText("Start Date");

        labelLevel1.setText("Level");

        labelTeamInfo1.setText("Team Info");

        labelPosition1.setText("Position Title");
        labelPosition1.setToolTipText("");

        labelMobile1.setText("Phone Number");

        labelEmail1.setText("Email ID");

        txtName.setToolTipText("");

        txtLevel.setToolTipText("");

        txtTeamInfo.setToolTipText("");

        txtPosition.setToolTipText("");

        txtPhone.setToolTipText("");

        txtEmail.setToolTipText("");

        btnConfirm.setBackground(new java.awt.Color(255, 153, 0));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        errTxt.setForeground(new java.awt.Color(255, 51, 51));
        errTxt.setText("*This is a Mandatory Field");
        errTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        errTxt5.setForeground(new java.awt.Color(255, 51, 51));
        errTxt5.setText("*This is a Mandatory Field");
        errTxt5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        errTxt6.setForeground(new java.awt.Color(255, 51, 51));
        errTxt6.setText("*This is a Mandatory Field");
        errTxt6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        errTxt7.setForeground(new java.awt.Color(255, 51, 51));
        errTxt7.setText("*This is a Mandatory Field");
        errTxt7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        errTxt8.setForeground(new java.awt.Color(255, 51, 51));
        errTxt8.setText("*This is a Mandatory Field");
        errTxt8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        errTxt9.setForeground(new java.awt.Color(255, 51, 51));
        errTxt9.setText("*This is a Mandatory Field");
        errTxt9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCancel.setBackground(new java.awt.Color(255, 153, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelEmpID1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelStartDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTeamInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81)
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtPosition, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(fixed_EmpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fixed_Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fixed_Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fixed_Age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(labelCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(errTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errTxt8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(errTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(displayPic, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(labelCreate1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errTxt))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fixed_EmpID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addComponent(labelEmpID1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixed_Age))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixed_Gender))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStartDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixed_Date))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errTxt5))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTeamInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errTxt6))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPosition1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errTxt7))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMobile1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errTxt8))
                        .addGap(18, 18, 18)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errTxt9))
                        .addGap(66, 66, 66)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirm)
                            .addComponent(btnCancel))
                        .addGap(45, 45, 45))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addComponent(displayPic, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        errTxt.setVisible(false);
        errTxt5.setVisible(false);
        errTxt6.setVisible(false);
        errTxt7.setVisible(false);
        errTxt8.setVisible(false);
        errTxt9.setVisible(false);

        jTabbedPane1.addTab("tab4", updatePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empTableMouseClicked
        emp = new employeeDetails();
        String empID=empTable.getValueAt( empTable.getSelectedRow(), 0).toString();
        String name=empTable.getValueAt( empTable.getSelectedRow(), 1).toString();
        String age= empTable.getValueAt(empTable.getSelectedRow(), 2).toString();
        String gender=empTable.getValueAt( empTable.getSelectedRow(), 3).toString();
        Date date=(Date) empTable.getValueAt( empTable.getSelectedRow(), 4);
        String level=empTable.getValueAt( empTable.getSelectedRow(), 5).toString();
        String info=empTable.getValueAt( empTable.getSelectedRow(), 6).toString();
        String position=empTable.getValueAt( empTable.getSelectedRow(), 7).toString();
        String mobile=empTable.getValueAt( empTable.getSelectedRow(), 8).toString();
        String mail=empTable.getValueAt( empTable.getSelectedRow(), 9).toString();
        String photo=empTable.getValueAt( empTable.getSelectedRow(), 10).toString();
        contactInfo contact = new contactInfo();
        contact.setContactDetails(mobile, mail);
        emp.setContact(contact);
        emp.setEmployeeDetails(name , Integer.parseInt(age), gender, date, Integer.parseInt(level), info, position,photo);
        empId=Integer.parseInt(empID);
        //to display profile
        jTabbedPane1.setSelectedIndex(1);
        label_displayName.setText(name);
        label_displayEmpID.setText(empID);
        label_displayAge.setText(age);
        label_displayDate.setText(date +"");
        label_displayPhone.setText(mobile);
        label_displayPosition.setText(position);
        label_displayEmail.setText(mail);
        label_displayGender.setText(gender);
        label_displayTeamInfo.setText(info);
        label_displayLevel.setText(level);
        ImageIcon profilePicture = new ImageIcon(photo);
        Image image = profilePicture.getImage().getScaledInstance(profilePhoto.getWidth(), profilePhoto.getHeight(), Image.SCALE_SMOOTH);
        profilePhoto.setIcon(new ImageIcon(image));       
        //to update Employee        
    }//GEN-LAST:event_empTableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        employeeList.deleteEmployee(empId) ;    
        JOptionPane.showMessageDialog(this,"Employee Profile has been deleted!!");
        displayEmployees(employeeList);
        jTabbedPane1.setSelectedIndex(0);             
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        clearErrorText();       
        if(validateFields()){            
            contact = new contactInfo();
            employee= new employeeDetails();         
            contact.setContactDetails(txtPhone.getText(), txtEmail.getText());
            employee.setContact(contact);
            employee.setEmployeeDetails(txtName.getText(), emp.getAge(), emp.getGender(), emp.getStartDate(), Integer.parseInt(txtLevel.getText()), txtTeamInfo.getText(), txtPosition.getText(),emp.getProfilePhoto());
            employeeList.updateEmployee(employee);
            clearFields();
            JOptionPane.showMessageDialog(null, employee.getName() +"'s profile has been updated.");
            displayEmployees(employeeList);
             jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearFields();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        txtName.setText(emp.getName());
        fixed_EmpID.setText(emp.getEmployeeID()+"");
        fixed_Age.setText(emp.getAge()+"");
        fixed_Date.setText(emp.getStartDate()+"");
        txtPhone.setText(emp.getContact().getPhoneNumber());
        txtPosition.setText(emp.getPositionTitle());
        txtEmail.setText(emp.getContact().getEmailID());
        fixed_Gender.setText(emp.getGender());
        txtTeamInfo.setText(emp.getTeamInfo());
        txtLevel.setText(emp.getLevel()+"");
        ImageIcon profilePicture = new ImageIcon(emp.getProfilePhoto());
        Image image = profilePicture.getImage().getScaledInstance(displayPic.getWidth(), displayPic.getHeight(), Image.SCALE_SMOOTH);
        displayPic.setIcon(new ImageIcon(image)); 
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txt_NameSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NameSearchKeyPressed
         
    }//GEN-LAST:event_txt_NameSearchKeyPressed

    private void txt_NameSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NameSearchKeyReleased
       txt_emailSearch.setText("");
       txt_EmpIDSearch.setText("");
        if(!txt_NameSearch.getText().isBlank()){
             filteredList = new employeeDirectory();
             for(employeeDetails emp : employeeList.getEmployeeList()){
                 if((emp.getName().toLowerCase()).contains(txt_NameSearch.getText().toLowerCase())){
                  filteredList.addEmployee(emp);
                 }
             }
             displayEmployees(filteredList);
             if(filteredList.getEmployeeList().isEmpty()){
                 JOptionPane.showMessageDialog(null, "No Results Found");
             }            
         }
         else{
         displayEmployees(employeeList);
         }
    }//GEN-LAST:event_txt_NameSearchKeyReleased

    private void txt_NameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameSearchActionPerformed

    private void txt_emailSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailSearchActionPerformed

    private void txt_emailSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailSearchKeyReleased
        txt_NameSearch.setText("");
        txt_EmpIDSearch.setText("");
        if(!txt_emailSearch.getText().isBlank()){
             filteredList = new employeeDirectory();
             for(employeeDetails emp : employeeList.getEmployeeList()){
                 if((emp.getName().toLowerCase()).contains(txt_emailSearch.getText().toLowerCase())){
                  filteredList.addEmployee(emp);
                 }
             }
             displayEmployees(filteredList);
             if(filteredList.getEmployeeList().isEmpty()){
                 JOptionPane.showMessageDialog(null, "No Results Found");
             }             
         }
         else{
         displayEmployees(employeeList);
         }
    }//GEN-LAST:event_txt_emailSearchKeyReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
      txt_emailSearch.setText("");
      txt_NameSearch.setText("");
        if(!txt_EmpIDSearch.getText().isBlank() && txt_EmpIDSearch.getText().matches("\\d+")){
             filteredList = new employeeDirectory();
             for(employeeDetails emp : employeeList.getEmployeeList()){
                 if(emp.getEmployeeID()==Integer.parseInt(txt_EmpIDSearch.getText())){
                  filteredList.addEmployee(emp);
                 }
             }
             displayEmployees(filteredList);
             if(filteredList.getEmployeeList().isEmpty()){
                 JOptionPane.showMessageDialog(null, "No Results Found");
             }             
         }
         else{
         JOptionPane.showMessageDialog(null, "Enter a Valid Employee ID");
         txt_EmpIDSearch.setText("");
         displayEmployees(employeeList);
         }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void  clearErrorText(){
        errTxt.setVisible(false);      
        errTxt5.setVisible(false);
        errTxt6.setVisible(false);
        errTxt7.setVisible(false);
        errTxt8.setVisible(false);
        errTxt9.setVisible(false);       
    }
    private void  clearFields(){
         txtName.setText("");         
         txtName.setText("");
         txtName.setText("");
         txtPhone.setText("");
         txtEmail.setText("");
         txtLevel.setText("");
         txtPosition.setText("");
         txtTeamInfo.setText("");  
         fixed_EmpID.setText("");
         fixed_Age.setText("");
         fixed_Date.setText("");
         fixed_Gender.setText("");
     }
    private boolean validateFields(){      
        boolean  valid=true;
        if(txtName.getText().isEmpty()){
            errTxt.setVisible(true);
            valid=false;
        }              
        if(txtLevel.getText().isEmpty()){
            errTxt5.setVisible(true);
            valid=false;
        }       
        if(txtTeamInfo.getText().isEmpty()){
            errTxt6.setVisible(true);
            valid=false;
        }        
        if(txtPosition.getText().isEmpty()){
            errTxt7.setVisible(true);
            valid=false;
        }        
        if(txtEmail.getText().isEmpty()){
            errTxt9.setVisible(true);
            valid=false;
        }
        if(txtPhone.getText().isEmpty()){
            errTxt8.setVisible(true);
            valid=false;
        }         
        if(txtPhone.getText().length()!=10 || !txtPhone.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Phone Number");
            valid=false;
        }
        if(txtLevel.getText().length()>2 || !txtLevel.getText().matches("\\d+")){
            JOptionPane.showMessageDialog(this,"Please Enter Level between 1-15");
            valid=false;
        }  
        if(txtEmail.getText().length()<2 || !txtEmail.getText().matches("^(.+)@(\\S+)$")){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Email");
            valid=false;
        }       
        return valid;
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel displayPic;
    private javax.swing.JPanel empPanel;
    private javax.swing.JTable empTable;
    private javax.swing.JLabel errTxt;
    private javax.swing.JLabel errTxt5;
    private javax.swing.JLabel errTxt6;
    private javax.swing.JLabel errTxt7;
    private javax.swing.JLabel errTxt8;
    private javax.swing.JLabel errTxt9;
    private javax.swing.JLabel fixed_Age;
    private javax.swing.JLabel fixed_Date;
    private javax.swing.JLabel fixed_EmpID;
    private javax.swing.JLabel fixed_Gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelAge1;
    private javax.swing.JLabel labelCreate;
    private javax.swing.JLabel labelCreate1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelEmpID;
    private javax.swing.JLabel labelEmpID1;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelGender1;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JLabel labelLevel1;
    private javax.swing.JLabel labelMobile;
    private javax.swing.JLabel labelMobile1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName1;
    private javax.swing.JLabel labelPosition;
    private javax.swing.JLabel labelPosition1;
    private javax.swing.JLabel labelStartDate;
    private javax.swing.JLabel labelStartDate1;
    private javax.swing.JLabel labelTeamInfo;
    private javax.swing.JLabel labelTeamInfo1;
    private javax.swing.JLabel label_displayAge;
    private javax.swing.JLabel label_displayDate;
    private javax.swing.JLabel label_displayEmail;
    private javax.swing.JLabel label_displayEmpID;
    private javax.swing.JLabel label_displayGender;
    private javax.swing.JLabel label_displayLevel;
    private javax.swing.JLabel label_displayName;
    private javax.swing.JLabel label_displayPhone;
    private javax.swing.JLabel label_displayPosition;
    private javax.swing.JLabel label_displayTeamInfo;
    private javax.swing.JPanel listPanel;
    private javax.swing.JLabel profilePhoto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtTeamInfo;
    private javax.swing.JTextField txt_EmpIDSearch;
    private javax.swing.JTextField txt_NameSearch;
    private javax.swing.JTextField txt_emailSearch;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
